// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYekBdWE1tburRNK3EJR5b7_uYH1NGHr8',
    appId: '1:54002399909:web:6f355b1d930539b2202b4c',
    messagingSenderId: '54002399909',
    projectId: 'bakeflow-erp',
    authDomain: 'bakeflow-erp.firebaseapp.com',
    storageBucket: 'bakeflow-erp.firebasestorage.app',
    measurementId: 'G-2C2495V9MN',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYekBdWE1tburRNK3EJR5b7_uYH1NGHr8',
    appId: '1:54002399909:web:6f355b1d930539b2202b4c',
    messagingSenderId: '54002399909',
    projectId: 'bakeflow-erp',
    authDomain: 'bakeflow-erp.firebaseapp.com',
    storageBucket: 'bakeflow-erp.firebasestorage.app',
    measurementId: 'G-2C2495V9MN',
  );
}